# Generated by Django 6.0 on 2025-12-15 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_size', models.IntegerField(default=1)),
                ('active_count', models.IntegerField(default=0)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('expired', 'Expired')], default='available', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released')], default='active', max_length=20)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='launcher.license')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tool_type', models.CharField(choices=[('desktop', 'Desktop'), ('web', 'Web')], default='desktop', max_length=20)),
                ('executable_path', models.CharField(blank=True, max_length=1000)),
                ('linux_executable_path', models.CharField(blank=True, max_length=1000)),
                ('windows_executable_path', models.CharField(blank=True, max_length=1000)),
                ('web_url', models.CharField(blank=True, max_length=1000)),
                ('requires_license', models.BooleanField(default=False)),
                ('env_template', models.JSONField(blank=True, default=dict)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='launcher.category')),
            ],
        ),
        migrations.AddField(
            model_name='license',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='launcher.tool'),
        ),
        migrations.CreateModel(
            name='EnvConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('vars', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envs', to='launcher.tool')),
            ],
        ),
    ]
