# Generated by Django 6.0.1 on 2026-01-12 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_size', models.IntegerField(default=1)),
                ('active_count', models.IntegerField(default=0)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('expired', 'Expired')], default='available', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_template', models.CharField(help_text='Example: launcher/presentation/detail.html', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('css_file', models.CharField(help_text='Example: css/themes/dark.css', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RunArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('image', 'Image'), ('metadata', 'Metadata'), ('log', 'Log'), ('gds', 'GDS'), ('report', 'Report')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released')], default='active', max_length=20)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='launcher.license')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='launcher.presentationtemplate')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='launcher.presentationtheme')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='launcher.presentation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SlideItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('image', 'Image'), ('log_snippet', 'Log Snippet'), ('attachment', 'Attachment')], max_length=20)),
                ('config', models.JSONField(blank=True, null=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='launcher.runartifact')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='launcher.slide')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tool_type', models.CharField(choices=[('desktop', 'Desktop'), ('web', 'Web')], default='desktop', max_length=20)),
                ('executable_path', models.CharField(blank=True, max_length=1000)),
                ('linux_executable_path', models.CharField(blank=True, max_length=1000)),
                ('windows_executable_path', models.CharField(blank=True, max_length=1000)),
                ('web_url', models.CharField(blank=True, max_length=1000)),
                ('requires_license', models.BooleanField(default=False)),
                ('env_template', models.JSONField(blank=True, default=dict)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='launcher.category')),
            ],
        ),
        migrations.AddField(
            model_name='license',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='launcher.tool'),
        ),
        migrations.CreateModel(
            name='EnvConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('vars', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envs', to='launcher.tool')),
            ],
        ),
        migrations.CreateModel(
            name='ToolRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.CharField(blank=True, max_length=255)),
                ('run_dir', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='launcher.tool')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='runartifact',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='launcher.toolrun'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='launcher.toolrun'),
        ),
        migrations.CreateModel(
            name='LayoutMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_count', models.IntegerField(blank=True, null=True)),
                ('dbu', models.FloatField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, help_text='Layout bounding box', null=True)),
                ('layers', models.JSONField(blank=True, help_text='List of layers', null=True)),
                ('png_preview', models.CharField(blank=True, help_text='Path to generated PNG preview', max_length=255)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout_metadata', to='launcher.toolrun')),
            ],
        ),
    ]
