# Generated by Django 6.0 on 2025-12-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0002_toolrun_layoutmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutmetadata',
            name='bbox',
            field=models.JSONField(blank=True, help_text='Layout bounding box', null=True),
        ),
        migrations.AlterField(
            model_name='layoutmetadata',
            name='layers',
            field=models.JSONField(blank=True, help_text='List of layers', null=True),
        ),
        migrations.AlterField(
            model_name='toolrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20),
        ),
    ]
