# Generated by Django 6.0 on 2025-12-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0003_alter_layoutmetadata_bbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolrun',
            name='run_dir',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
